config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :tasks
  get '/tasks', to: 'tasks#index', as: :tasks
  get '/tasks/new', to: 'tasks#new', as: :new_task
  get '/tasks/:id', to: 'tasks#show', as: :task
  # post '/tasks', to: 'tasks#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  # def create
  #   @task = Task.new(params[:task])
  #   @task.save
  #   redirect_to tasks_path
  # end

  # private

  # def set_task
  #   @task = Task.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
    <h3><%= task.completed ? "[X]" : "[ ]" %> <%= link_to task.title, task_path(task) %></h3>
<% end %>

<h3><%= link_to 'Create a new task', new_task_path %></h3>

app/views/tasks/new.html.erb
<h1>new task</h1>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p> Task completed? <%=@task.completed ? "[X]" : "[ ]"%></p>
<p><%= link_to "Back to list", tasks_path %></p>